### ISSUE TITLE
JS Capstone Kanban Project Board

### ISSUE THREAD

**Issue by hsztan** [hsztan/cap-js#22]
https://github.com/users/hsztan/projects/3
There are two memebers in our project.

**Comment by Lordkaito** [comment]
Hi @hsztan, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Please provide a valid link to review your project. Right now, your link seems to be broken. Also, if I look at the project by myself, I cannot see any, so please make sure you submitted the link to the correct repository.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hsztan** [comment]
Hi @Lordkaito, as requested in the instructions, I made the project private, which I assumed would be a problem, but I still followed the instructions. I have changed the project to the public. You should be able to see it now. Thanks for your understanding. 😎

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @hsztan and @Tadesse-Alemayehu,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
